CREATE TABLE chzzk_oauth_token (
  channel_id VARCHAR2(100 CHAR) PRIMARY KEY,
  access_token VARCHAR2(3000 CHAR) NOT NULL,
  refresh_token VARCHAR2(3000 CHAR),
  token_type VARCHAR2(30 CHAR),
  scope VARCHAR2(1000 CHAR),
  access_token_expires_at TIMESTAMP WITH TIME ZONE,
  refresh_token_expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
