CREATE TABLE youtube_channel (
    channel_id VARCHAR2(64) NOT NULL PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    thumbnail_url VARCHAR2(1000),
    currently_live NUMBER(1) DEFAULT 0 NOT NULL,
    current_live_video_id VARCHAR2(64),
    last_video_id VARCHAR2(64),
    last_checked_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE youtube_subscription (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    youtube_channel_id VARCHAR2(64) NOT NULL,
    type VARCHAR2(32) NOT NULL,
    webhook_id NUMBER NOT NULL,
    form_owner VARCHAR2(255) NOT NULL,
    language VARCHAR2(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    interval_minute NUMBER DEFAULT 10 NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    bot_profile_id NUMBER NOT NULL,
    content VARCHAR2(2000),
    color_hex VARCHAR2(11) DEFAULT 'ff0000' NOT NULL,
    CONSTRAINT fk_yt_sub_channel_id FOREIGN KEY (youtube_channel_id) REFERENCES youtube_channel(channel_id),
    CONSTRAINT fk_yt_sub_webhook_id FOREIGN KEY (webhook_id) REFERENCES discord_webhook_data(id),
    CONSTRAINT fk_yt_sub_owner_id FOREIGN KEY (form_owner) REFERENCES chzzk_channel(channel_id),
    CONSTRAINT fk_yt_sub_bot_profile_id FOREIGN KEY (bot_profile_id) REFERENCES discord_bot_profile_data(id)
);

CREATE TABLE youtube_notification_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id NUMBER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_yt_log_subscription_id FOREIGN KEY (subscription_id) REFERENCES youtube_subscription(id)
);
