CREATE TABLE twitch_event_subscription (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_channel_id VARCHAR2(255) NOT NULL,
  broadcaster_user_id VARCHAR2(255) NOT NULL,
  broadcaster_login VARCHAR2(255) NOT NULL,
  broadcaster_display_name VARCHAR2(255) NOT NULL,
  discord_webhook_url VARCHAR2(30000) NOT NULL,
  eventsub_online_id VARCHAR2(255),
  eventsub_offline_id VARCHAR2(255),
  enabled NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
