CREATE TABLE IF NOT EXISTS chzzk_channel (
  channel_id VARCHAR(255) PRIMARY KEY,
  channel_name VARCHAR(33) NOT NULL,
  profile_url VARCHAR(30000),
  is_verified_mark BOOLEAN NOT NULL DEFAULT false,
  channel_description VARCHAR(550),
  subscription_availability BOOLEAN NOT NULL DEFAULT false,
  is_live BOOLEAN NOT NULL DEFAULT false,
  follower_count INTEGER NOT NULL DEFAULT 0,
  last_check_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS discord_webhook_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(500) NOT NULL,
  webhook_url VARCHAR(30000) NOT NULL,
  meno VARCHAR(500),
  owner_id VARCHAR(255) NOT NULL,
  CONSTRAINT fk_discord_webhook_data_owner_id
    FOREIGN KEY (owner_id) REFERENCES chzzk_channel(channel_id)
);

CREATE TABLE IF NOT EXISTS chzzk_category (
  category_id VARCHAR(255) NOT NULL,
  category_type VARCHAR(255) NOT NULL,
  category_name VARCHAR(255) NOT NULL,
  poster_image_url VARCHAR(30000),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (category_id, category_type)
);

CREATE TABLE IF NOT EXISTS discord_bot_profile_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id VARCHAR(255) NOT NULL,
  username VARCHAR(100) NOT NULL,
  avatar_url VARCHAR(30000) NOT NULL,
  CONSTRAINT fk_bot_profile_data_owner_id
    FOREIGN KEY (owner_id) REFERENCES chzzk_channel(channel_id)
);

CREATE TABLE IF NOT EXISTS chzzk_subscription_form (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_id VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  webhook_id BIGINT NOT NULL,
  form_owner VARCHAR(255) NOT NULL,
  language VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  interval_minute INTEGER NOT NULL DEFAULT 10,
  enabled BOOLEAN NOT NULL DEFAULT false,
  bot_profile_id BIGINT NOT NULL,
  content VARCHAR(2000),
  color_hex VARCHAR(11) NOT NULL DEFAULT '000000',
  CONSTRAINT fk_chzzk_subscription_form_channel_id
    FOREIGN KEY (channel_id) REFERENCES chzzk_channel(channel_id),
  CONSTRAINT fk_chzzk_subscription_form_webhook_id
    FOREIGN KEY (webhook_id) REFERENCES discord_webhook_data(id),
  CONSTRAINT fk_chzzk_subscription_form_owner_channel_id
    FOREIGN KEY (form_owner) REFERENCES chzzk_channel(channel_id),
  CONSTRAINT fk_chzzk_subscription_form_bot_profile_id
    FOREIGN KEY (bot_profile_id) REFERENCES discord_bot_profile_data(id)
);

CREATE TABLE IF NOT EXISTS chzzk_subscription_stream_online_form (
  id BIGINT PRIMARY KEY,
  show_detail BOOLEAN NOT NULL DEFAULT false,
  show_thumbnail BOOLEAN NOT NULL DEFAULT true,
  show_viewer_count BOOLEAN NOT NULL DEFAULT false,
  show_tag BOOLEAN NOT NULL DEFAULT true,
  CONSTRAINT fk_chzzk_subscription_stream_online_form_id
    FOREIGN KEY (id) REFERENCES chzzk_subscription_form(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notification_log (
  log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_notification_log_form_id
    FOREIGN KEY (form_id) REFERENCES chzzk_subscription_form(id)
);
