CREATE TABLE youtube_channel (
    channel_id VARCHAR(64) NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    thumbnail_url VARCHAR(1000),
    currently_live BOOLEAN NOT NULL DEFAULT FALSE,
    current_live_video_id VARCHAR(64),
    last_video_id VARCHAR(64),
    last_checked_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE youtube_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    youtube_channel_id VARCHAR(64) NOT NULL,
    type VARCHAR(32) NOT NULL,
    webhook_id BIGINT NOT NULL,
    form_owner VARCHAR(255) NOT NULL,
    language VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    interval_minute INTEGER NOT NULL DEFAULT 10,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    bot_profile_id BIGINT NOT NULL,
    content VARCHAR(2000),
    color_hex VARCHAR(11) NOT NULL DEFAULT 'ff0000',
    CONSTRAINT fk_youtube_subscription_channel_id FOREIGN KEY (youtube_channel_id) REFERENCES youtube_channel(channel_id),
    CONSTRAINT fk_youtube_subscription_webhook_id FOREIGN KEY (webhook_id) REFERENCES discord_webhook_data(id),
    CONSTRAINT fk_youtube_subscription_owner_channel_id FOREIGN KEY (form_owner) REFERENCES chzzk_channel(channel_id),
    CONSTRAINT fk_youtube_subscription_bot_profile_id FOREIGN KEY (bot_profile_id) REFERENCES discord_bot_profile_data(id)
);

CREATE TABLE youtube_notification_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_youtube_notification_log_subscription_id FOREIGN KEY (subscription_id) REFERENCES youtube_subscription(id)
);
