CREATE TABLE IF NOT EXISTS twitch_event_subscription (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_channel_id VARCHAR(255) NOT NULL,
  broadcaster_user_id VARCHAR(255) NOT NULL,
  broadcaster_login VARCHAR(255) NOT NULL,
  broadcaster_display_name VARCHAR(255) NOT NULL,
  discord_webhook_url VARCHAR(30000) NOT NULL,
  eventsub_online_id VARCHAR(255),
  eventsub_offline_id VARCHAR(255),
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
